export const env = {
    PERSONAL_NAME: process.env.NEXT_PUBLIC_PERSONAL_NAME || '',
    GITHUB_USERNAME: process.env.NEXT_PUBLIC_GITHUB_USERNAME || '',
    GITHUB_REPOSITORIES_TYPE: process.env.NEXT_PUBLIC_GITHUB_REPOSITORIES_TYPE || '',
    FILE_NAME_EXPORT: process.env.NEXT_PUBLIC_FILE_NAME_EXPORT || '',
}
